services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-clinica
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - tts-api

  tts-api:
    build: ./tts-api
    container_name: tts-api-clinica
    restart: always
    expose:
      - "5000"
    volumes:
      - tts_audios:/app/audios

volumes:
  n8n_data:
  tts_audios:
